channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    -  gradio==3.36.1
    -  h3==3.7.6
    -  matplotlib==3.7.1
    -  numpy==1.25.0
    -  pandas==2.0.3
    -  scikit_learn==1.3.0
    -  scikit-image==0.19.3
    -  tifffile==2023.7.4
    -  torch==1.12.1
    -  imagecodecs==2023.9.18
